---
title:."ANVOA"
author:."Anna.MacFarlane"
date:."2/8/2021"
output:.pdf_document
---

Non-functional code 

```{r setup,include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(broom)

data<-read.csv("memriFullCorrect.csv")

data<-data%>%
  filter(! is.na(Proportional.Medial_Orbital_Cortex.Volume))%>%
  filter(! is.na(genotype))%>%
  filter(genotype!="")%>%
  filter(genotype!="HN")%>%
  mutate(genotype=case_when(
    genotype=="APOE2"|genotype=="APOE22"~"APOE2",
    #genotype.==."APOE22".~."APOE2",
    genotype=="APOE3"|genotype=="APOE33"~"APOE3",
    #genotype.==."APOE33".~."APOE3",
    genotype=="CVN"~"CVN"
  ))%>%
   group_by(genotype)

view(data)

geno <- data$genotype
#regions<-cbind(data.frame(11:229))
#region<-data.frame(cbind(regions))
```

```{r left}
regionsLeft <- cbind(data$Proportional.Cingulate_Cortex_Area_24a.Volume,
data$Proportional.Cingulate_Cortex_Area_24a_prime.Volume,
data$Proportional.Cingulate_Cortex_Area_24b.Volume,
data$Proportional.Cingulate_Cortex_Area_24b_prime.Volume,
data$Proportional.Cingulate_Cortex_Area_29a.Volume,
data$Proportional.Cingulate_Cortex_Area_29b.Volume,
data$Proportional.Cingulate_Cortex_Area_29c.Volume,
data$Proportional.Cingulate_Cortex_Area_30.Volume,
data$Proportional.Cingulate_Cortex_Area_32.Volume,
data$Proportional.Primary_Auditory_Cortex.Volume,
data$Proportional.Secondary_Auditory_Cortex_Dorsal_Part.Volume,
data$Proportional.Secondary_Auditory_Cortex_Ventral_Part.Volume,
data$Proportional.Dorsolateral_Orbital_Cortex.Volume,
data$Proportional.Frontal_Cortex_Area_3.Volume,
data$Proportional.Frontal_Association_Cortex.Volume,
data$Proportional.Insular_Cortex.Volume,
data$Proportional.Lateral_Orbital_Cortex.Volume,
data$Proportional.Lateral_Parietal_Association_Cortex.Volume,
data$Proportional.Primary_Motor_Cortex.Volume,
data$Proportional.Secondary_Motor_Cortex.Volume,
data$Proportional.Medial_Orbital_Cortex.Volume,
data$Proportional.Medial_Parietal_Association_Cortex.Volume,
data$Proportional.Parietal_Cortex_Posterior_Area_Rostral_Part.Volume,
data$Proportional.Primary_Somatosensory_Cortex.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Barrel_Field.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Dysgranular_Zone.Volume,
data$Proportional.Primary_Somatosensory_CortexForelimb_Region.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Hindlimb_Region.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Jaw_Region.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Shoulder_Region.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Trunk_Region.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Upper_Lip_Region.Volume,
data$Proportional.Secondary_Somatosensory_Cortex.Volume,
data$Proportional.Temporal_Association_Cortex.Volume,
data$Proportional.Primary_Visual_Cortex.Volume,
data$Proportional.Primary_Visual_Cortex_Binocular_Area.Volume,
data$Proportional.Primary_Visual_Cortex_Monocular_Area.Volume,
data$Proportional.Secondary_Visual_CortexLateral_Area.Volume,
data$Proportional.Secondary_Visual_Cortex_Mediolateral_Area.Volume,
data$Proportional.Secondary_Visual_Cortex_Mediomedial_Area.Volume,
data$Proportional.Ventral_Orbital_Cortex.Volume,
data$Proportional.Caudomedial_Entorhinal_Cortex.Volume,
data$Proportional.Dorsal_Intermediate_Entorhinal_Cortex.Volume,
data$Proportional.Dorsolateral_Entorhinal_Cortex.Volume,
data$Proportional.Medial_Entorhinal_Cortex.Volume,
data$Proportional.Ventral_Intermediate_Entorhinal_Cortex.Volume,
data$Proportional.Claustrum.Volume,
data$Proportional.Dorsal_Claustrum.Volume,
data$Proportional.Posterolateral_Cortical_Amygdaloid_Area.Volume,
data$Proportional.Ventral_Claustrum.Volume,
data$Proportional.Hippocampal.Volume,
data$Proportional.Dorsal_Tenia_Tecta.Volume,
data$Proportional.Ectorhinal.Cortex.Volume,
data$Proportional.Parasubiculum.Volume,
data$Proportional.Perirhinal_Cortex.Volume,
data$Proportional.Presubiculum.Volume,
data$Proportional.Piriform_Cortex.Volume,
data$Proportional.Amygdalopiriform_Transition_Area.Volume,
data$Proportional.Hypothalamus.Volume,
data$Proportional.Preoptic_Telencephalon.Volume,
data$Proportional.Subthalamic_Nucleus.Volume,
data$Proportional.Septum.Volume,
data$Proportional.Globus_Pallidus.Volume,
data$Proportional.Striatum.Volume,
data$Proportional.Amygdala.Volume,
data$Proportional.Accumbens.Volume,
data$Proportional.Bed_Nucleus_of_the_Stria_Terminalis.Volume,
data$Proportional.Ventral_Pallidum.Volume,
data$Proportional.Periaquaductal_Grey.Volume,
data$Proportional.Anterior_Pretectal_Nucleus.Volume,
data$Proportional.Ventral_Tegmental_Area.Volume,
data$Proportional.Thalamus_Rest.Volume,
data$Proportional.Ventral_Thalamic_Nuclei.Volume,
data$Proportional.Latero_Dorsal_Nucleus_of_Thalamus.Volume,
data$Proportional.Medial_Geniculate_Nucleus.Volume,
data$Proportional.Lateral_Geniculate_Nucleus.Volume,
data$Proportional.Zona_Incerta.Volume,
data$Proportional.Reticular_Nucleus_of_Thalamus.Volume,
data$Proportional.Subbrachial_Nucleus_and_Peripeduncular_Nucleus.Volume,
data$Proportional.Deep_Mesencephalic_Nuclei.Volume,
data$Proportional.Superior_Colliculus.Volume,
data$Proportional.Inferior_Colliculus.Volume,
data$Proportional.Substantia_Nigra.Volume,
data$Proportional.Red_Nucleus_Parvicellular.Volume,
data$Proportional.Midbrain_Reticular_Nucleus.Volume,
data$Proportional.Rostral_Linear_Nucleus.Volume,
data$Proportional.Cuneiform_Nucleus.Volume,
data$Proportional.Precuneiform_Nucleus.Volume,
data$Proportional.Brain_Stem_Rest.Volume,
data$Proportional.Interpeduncular_Nucleus.Volume,
data$Proportional.Cerebellar_Cortex.Volume,
#data$Proportional.Dentate_Lateral_Nucleus_of_Cerebellum.Volume,
data$Proportional.Interposed_Nucleus_of_Cerebellum.Volume,
data$Proportional.Fastigial_Medial_Dorsolateral_Nucleus_of_Cerebellum.Volume,
data$Proportional.Fastigial_Medial_Nucleus_of_Cerebellum.Volume,
data$Proportional.Ventral_Lateral_Lemniscus_Nucleus.Volume,
data$Proportional.Parabrachial_Nucleus.Volume,
data$Proportional.Parabrachial_Medial_Nucleus_and_Koelliker_Fuse_Nucleus.Volume,
data$Proportional.Parvicellular_Reticular_Nucleus_and_Principal_Sensory_Trigeminal_Nucleus.Volume,
data$Proportional.Central_Gray.Volume,
data$Proportional.Pedunculotegmental_Medial_Paralemniscial_and_Supratrigemnial_Nuclei.Volume,
data$Proportional.Motor_Root_of_Trigeminal_Nerve.Volume,
data$Proportional.Trigeminal_Motor_Nucleus.Volume,
data$Proportional.Pontine_Reticular_NucleusOral.Volume,
data$Proportional.Raphe_Nucleus.Volume,
data$Proportional.Trigeminal_Sensory_Nucleus.Volume,
data$Proportional.Dorsal_Tegmentum.Volume,
data$Proportional.Tegmental_Nucleus.Volume,
data$Proportional.Cochlear_Nucleus.Volume,
data$Proportional.Pontine_Nucleus.Volume,
data$Proportional.Reticulotegmental_Nucleus_of_Pons.Volume,
data$Proportional.Olivary_Complex.Volume,
data$Proportional.Pontine_Reticular_NucleusCaudal.Volume,
data$Proportional.Spinal_Trigeminal_Nucleus.Volume,
data$Proportional.Vestibular_Nuclei.Volume,
data$Proportional.Gigantocellular_Reticular_Nucleus.Volume,
data$Proportional.Cuneate_Nucleus.Volume,
data$Proportional.Anterior_Commisure.Volume,
data$Proportional.Optic_Tracts.Volume,
data$Proportional.Fimbria.Volume,
data$Proportional.Corpus_Callosum.Volume,
data$Proportional.Fornix.Volume,
data$Proportional.Stria_Terminalis.Volume,
data$Proportional.Cingulum.Volume,
data$Proportional.Lateral_Olfactory_Tract.Volume,
data$Proportional.Ventral_Hippocampal_Commissure.Volume,
data$Proportional.Internal_Capsule.Volume,
data$Proportional.Fasciculus_Retroflexus.Volume,
data$Proportional.Stria_Medularis.Volume,
data$Proportional.Mamillothalamic_Tract.Volume,
data$Proportional.Posterior_Commissure.Volume,
data$Proportional.Brachium_of_Superior_Colliculus.Volume,
data$Proportional.Cerebral_Peduncle.Volume,
data$Proportional.Lateral_Lemniscus.Volume,
data$Proportional.Spinal_Trigeminal_Nerve.Volume,
data$Proportional.Pyramidal_Tract.Volume,
data$Proportional.Vestibulocochlear_Nerve.Volume,
data$Proportional.Facial_Nerve.Volume,
data$Proportional.Longitudinal_Fasciculus_of_Pons.Volume,
data$Proportional.Medial_Longitudinal_Fasciculus_and_Tectospinal_Tract.Volume,
data$Proportional.Spinocerebellar_Tract.Volume,
data$Proportional.Medial_Lemniscus.Volume,
data$Proportional.Ventral_Spinocerebellar_Tract.Volume,
data$Proportional.Middle_Cerebellar_Peduncle.Volume,
data$Proportional.Superior_Cerebellar_Peduncle.Volume,
data$Proportional.Inferior_Cerebellar_Peduncle.Volume,
data$Proportional.Cerebellar_White_Matter.Volume,
data$Proportional.Lateral.Ventricle.Volume,
data$Proportional.Cingulate_Cortex_Area_25.Volume,
data$Proportional.Dorsal_Acustic_Stria.Volume,
data$Proportional.Postsubiculum.Volume,
data$Proportional.Ventricular_System_4thVentricle.Volume,
#data$Proportional.Microcellular_Tegmental_Nucleus.Volume,
#data$Proportional.Pretectal_Nucleus.Volume,
data$Proportional.Latero_Dorsal_Thalamic_Nucleus_Ventro_Lateral.Volume,
data$Proportional.Latero_Posterior_Nuclei_of_Thalamus.Volume,
data$Proportional.Anterior_Thalamic_Nuclei.Volume,
data$Proportional.Red_Nucleus_Magnocellular.Volume,
data$Proportional.Pararubral_Nucleus.Volume,
data$Proportional.Retro_Rubral_Field.Volume,
data$Proportional.Cerebrospinal_fluid.Volume,
data$Proportional.IntermediateReticularNucleus.Volume,
data$Proportional.PosteriorDorsal_ParaventricularMedialParvicellular_Posterior_LateralHypothalamus.Volume,
data$Proportional.Prerubral_Forel.Volume,
data$Proportional.PVG_of_Hypothalamus.Volume,
data$Proportional.Basal.Lateral.Amygdala.Volume)
```

```{r right}
regionsRight<-cbind(data$Proportional.Cingulate_Cortex_Area_24a.R.Volume,
data$Proportional.Cingulate_Cortex_Area_24a_prime.R.Volume,
data$Proportional.Cingulate_Cortex_Area_24b.R.Volume,
data$Proportional.Cingulate_Cortex_Area_24b_prime.R.Volume,
data$Proportional.Cingulate_Cortex_Area_29a.R.Volume,
data$Proportional.Cingulate_Cortex_Area_29b.R.Volume,
data$Proportional.Cingulate_Cortex_Area_29c.R.Volume,
data$Proportional.Cingulate_Cortex_Area_30.R.Volume,
data$Proportional.Cingulate_Cortex_Area_32.R.Volume,
data$Proportional.Primary_Auditory_Cortex.R.Volume,
data$Proportional.Secondary_Auditory_Cortex_Dorsal_Part.R.Volume,
data$Proportional.Secondary_Auditory_Cortex_Ventral_Part.R.Volume,
data$Proportional.Dorsolateral_Orbital_Cortex.R.Volume,
data$Proportional.Frontal_Cortex_Area_3.R.Volume,
data$Proportional.Frontal_Association_Cortex.R.Volume,
data$Proportional.Insular_Cortex.R.Volume,
data$Proportional.Lateral_Orbital_Cortex.R.Volume,
data$Proportional.Lateral_Parietal_Association_Cortex.R.Volume,
data$Proportional.Primary_Motor_Cortex.R.Volume,
data$Proportional.Secondary_Motor_Cortex.R.Volume,
data$Proportional.Medial_Orbital_Cortex.R.Volume,
data$Proportional.Medial_Parietal_Association_Cortex.R.Volume,
data$Proportional.Parietal_Cortex_Posterior_Area_Rostral_Part.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Barrel_Field.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Dysgranular_Zone.R.Volume,
data$Proportional.Primary_Somatosensory_CortexForelimb_Region.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Hindlimb_Region.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Jaw_Region.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Shoulder_Region.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Trunk_Region.R.Volume,
data$Proportional.Primary_Somatosensory_Cortex_Upper_Lip_Region.R.Volume,
data$Proportional.Secondary_Somatosensory_Cortex.R.Volume,
data$Proportional.Temporal_Association_Cortex.R.Volume,
data$Proportional.Primary_Visual_Cortex.R.Volume,
data$Proportional.Primary_Visual_Cortex_Binocular_Area.R.Volume,
data$Proportional.Primary_Visual_Cortex_Monocular_Area.R.Volume,
data$Proportional.Secondary_Visual_CortexLateral_Area.R.Volume,
data$Proportional.Secondary_Visual_Cortex_Mediolateral_Area.R.Volume,
data$Proportional.Secondary_Visual_Cortex_Mediomedial_Area.R.Volume,
data$Proportional.Ventral_Orbital_Cortex.R.Volume,
data$Proportional.Caudomedial_Entorhinal_Cortex.R.Volume,
data$Proportional.Dorsal_Intermediate_Entorhinal_Cortex.R.Volume,
data$Proportional.Dorsolateral_Entorhinal_Cortex.R.Volume,
data$Proportional.Medial_Entorhinal_Cortex.R.Volume,
data$Proportional.Ventral_Intermediate_Entorhinal_Cortex.R.Volume,
data$Proportional.Claustrum.R.Volume,
data$Proportional.Dorsal_Claustrum.R.Volume,
data$Proportional.Posterolateral_Cortical_Amygdaloid_Area.R.Volume,
data$Proportional.Ventral_Claustrum.R.Volume,
data$Proportional.Hippocampus.R.Volume,
data$Proportional.Dorsal_Tenia_Tecta.R.Volume,
data$Proportional.Ectorhinal_Cortex.R.Volume,
data$Proportional.Parasubiculum.R.Volume,
data$Proportional.Perirhinal_Cortex.R.Volume,
data$Proportional.Presubiculum.R.Volume,
data$Proportional.Piriform_Cortex.R.Volume,
data$Proportional.Amygdalopiriform_Transition_Area.R.Volume,
data$Proportional.Hypothalamus.R.Volume,
data$Proportional.Preoptic_Telencephalon.R.Volume,
data$Proportional.Subthalamic_Nucleus.R.Volume,
data$Proportional.Septum.R.Volume,
data$Proportional.Globus_Pallidus.R.Volume,
data$Proportional.Striatum.R.Volume,
data$Proportional.Amygdala.R.Volume,
data$Proportional.Accumbens.R.Volume,
data$Proportional.Bed_Nucleus_of_the_Stria_Terminalis.R.Volume,
data$Proportional.Ventral_Pallidum.R.Volume,
data$Proportional.Periaquaductal_Grey.R.Volume,
data$Proportional.Anterior_Pretectal_Nucleus.R.Volume,
data$Proportional.Ventral_Tegmental_Area.R.Volume,
data$Proportional.Thalamus_Rest.R.Volume,
data$Proportional.Ventral_Thalamic_Nuclei.R.Volume,
data$Proportional.Latero_Dorsal_Nucleus_of_Thalamus.R.Volume,
data$Proportional.Medial_Geniculate_Nucleus.R.Volume,
data$Proportional.Lateral_Geniculate_Nucleus.R.Volume,
data$Proportional.Zona_Incerta.R.Volume,
data$Proportional.Reticular_Nucleus_of_Thalamus.R.Volume,
data$Proportional.Subbrachial_Nucleus_and_Peripeduncular_Nucleus.R.Volume,
data$Proportional.Deep_Mesencephalic_Nuclei.R.Volume,
data$Proportional.Superior_Colliculus.R.Volume,
data$Proportional.Inferior_Colliculus.R.Volume,
data$Proportional.Substantia_Nigra.R.Volume,
data$Proportional.Red_Nucleus_Parvicellular.R.Volume,
data$Proportional.Midbrain_Reticular_Nucleus.R.Volume,
data$Proportional.Rostral_Linear_Nucleus.R.Volume,
data$Proportional.Cuneiform_Nucleus.R.Volume,
data$Proportional.Precuneiform_Nucleus.R.Volume,
data$Proportional.Brain_Stem_Rest.R.Volume,
data$Proportional.Interpeduncular_Nucleus.R.Volume,
data$Proportional.Cerebellar_Cortex.R.Volume,
data$Proportional.Dentate_Lateral_Nucleus_of_Cerebellum.R.Volume,
data$Proportional.Interposed_Nucleus_of_Cerebellum.R.Volume,
data$Proportional.Fastigial_Medial_Dorsolateral_Nucleus_of_Cerebellum.R.Volume,
data$Proportional.Fastigial_Medial_Nucleus_of_Cerebellum.R.Volume,
data$Proportional.Ventral_Lateral_Lemniscus_Nucleus.R.Volume,
data$Proportional.Parabrachial_Nucleus.R.Volume,
data$Proportional.Parabrachial_Medial_Nucleus_and_Koelliker_Fuse_Nucleus.R.Volume,
data$Proportional.Parvicellular_Reticular_Nucleus_and_Principal_Sensory_Trigeminal_Nucleus.R.Volume,
data$Proportional.Central_Gray.R.Volume,
data$Proportional.Pedunculotegmental_Medial_Paralemniscial_and_Supratrigemnial_Nuclei.R.Volume,
data$Proportional.Motor_Root_of_Trigeminal_Nerve.R.Volume,
data$Proportional.Trigeminal_Motor_Nucleus.R.Volume,
data$Proportional.Pontine_Reticular_Nucleus.R.Volume,
data$Proportional.Raphe_Nucleus.R.Volume,
data$Proportional.Trigeminal_Sensory_Nucleus.R.Volume,
data$Proportional.Dorsal_Tegmentum.R.Volume,
data$Proportional.Tegmental_Nucleus.R.Volume,
data$Proportional.Cochlear_Nucleus.R.Volume,
data$Proportional.Pontine_Nucleus.R.Volume,
data$Proportional.Reticulotegmental_Nucleus_of_Pons.R.Volume,
data$Proportional.Olivary_Complex.R.Volume,
#data$Proportional.Pontine_Reticular_NucleusCaudal.R.Volume,
data$Proportional.Spinal_Trigeminal_Nucleus.R.Volume,
data$Proportional.Vestibular_Nuclei.R.Volume,
data$Proportional.Gigantocellular_Reticular_Nucleus.R.Volume,
data$Proportional.Cuneate_Nucleus.R.Volume,
data$Proportional.Anterior_Commisure.R.Volume,
data$Proportional.Optic_Tracts.R.Volume,
data$Proportional.Fimbria.R.Volume,
data$Proportional.Corpus_Callosum.R.Volume,
data$Proportional.Fornix.R.Volume,
data$Proportional.Stria_Terminalis.R.Volume,
data$Proportional.Cingulum.R.Volume,
data$Proportional.Lateral_Olfactory_Tract.R.Volume,
data$Proportional.Ventral_Hippocampal_Commissure.R.Volume,
data$Proportional.Internal_Capsule.R.Volume,
data$Proportional.Fasciculus_Retroflexus.R.Volume,
data$Proportional.Stria_Medularis.R.Volume,
data$Proportional.Mamillothalamic_Tract.R.Volume,
data$Proportional.Posterior_Commissure.R.Volume,
data$Proportional.Brachium_of_Superior_Colliculus.R.Volume,
data$Proportional.Cerebral_Peduncle.R.Volume,
data$Proportional.Lateral_Lemniscus.R.Volume,
data$Proportional.Spinal_Trigeminal_Nerve.R.Volume,
data$Proportional.Pyramidal_Tract.R.Volume,
data$Proportional.Vestibulocochlear_Nerve.R.Volume,
data$Proportional.Facial_Nerve.R.Volume,
data$Proportional.Longitudinal_Fasciculus_of_Pons.R.Volume,
data$Proportional.Medial_Longitudinal_Fasciculus_and_Tectospinal_Tract.R.Volume,
data$Proportional.Spinocerebellar_Tract.R.Volume,
data$Proportional.Medial_Lemniscus.R.Volume,
data$Proportional.Ventral_Spinocerebellar_Tract.R.Volume,
data$Proportional.Middle_Cerebellar_Peduncle.R.Volume,
data$Proportional.Superior_Cerebellar_Peduncle.R.Volume,
data$Proportional.Inferior_Cerebellar_Peduncle.R.Volume,
data$Proportional.Cerebellar_White_Matter.R.Volume,
data$Proportional.Lateral.Ventricle.R.Volume,
data$Proportional.Cingulate_Cortex_Area_25.R.Volume,
data$Proportional.Dorsal_Acustic_Stria.R.Volume,
data$Proportional.Postsubiculum.R.Volume,
data$Proportional.Ventricular_System_4thVentricle.R.Volume,
data$Proportional.Microcellular_Tegmental_Nucleus.R.Volume)
```

### ANOVA Graphs by Region

```{r anova-region}
col_names <- regionsLeft
col_names <- regionsLeft[-1]

for (i in col_names){
    plot <- ggplot(df, aes_string(x=df$genotype, y=i)) +
    geom_violin() + 
    geom_boxplot(width = 0.1, outlier.color = "red") +
    geom_jitter(height = 0, width = 0.3)
    print(plot)
}

```

### MANOVA Analysis

```{r analysis-left}
anovaLeft <- manova(regionsLeft ~ geno)
summary(anovaLeft, test="Pillai", tol=0)
#summary(anovaLeft, test="Hotelling-Lawley", tol=0)
```

```{r analysis-right}
anovaRight <- manova(regionsRight ~ geno)
summary(anovaLeft, test="Pillai", tol=0)
```