---
title: "Adjusted p-values for multiple comparisons"
author: "Anna MacFarlane"
date: "3/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)

corrLeft <- read.csv("corrLeft.csv")
corrRight <- read.csv("corrRight.csv")

apoe4right <- read.csv("right-sex-apoe4-significantvalues.csv")
apoe3right <- read.csv("right-sex-apoe3-significantvalues.csv")
apoe2right <- read.csv("right-sex-apoe2-significantvalues.csv")

apoe4left <- read.csv("left-sex-apoe4-significantvalues.csv")
apoe3left <- read.csv("left-sex-apoe3-significantvalues.csv")
apoe2left <- read.csv("left-sex-apoe2-significantvalues.csv")
```

## Left APOE4
```{r corrections-left-apoe4, echo = FALSE}
p.adjust(apoe4left$Pval, method = "fdr", n = 165)
```

## Left APOE3
```{r corrections-left-apoe3, echo = FALSE}
p.adjust(apoe3left$Pval, method = "fdr", n = 165)
```

## Left APOE2
```{r corrections-let-apoe2, echo = FALSE}
p.adjust(apoe2left$Pval, method = "fdr", n = 165)
```

## Right APOE2
```{r corrections-right-apoe2, echo = FALSE}
p.adjust(apoe2right$Pval, method = "fdr", n = 165)
```

## Right APOE3
```{r corrections-right-apoe3, echo = FALSE}
p.adjust(apoe3right$Pval, method = "fdr", n = 165)
```

## Right APOE4 
```{r corrections-right-apoe4, echo = FALSE}
p.adjust(apoe4right$pval, method = "fdr", n = 165)
```

## Left Hemisphere
```{r corrections-left, echo = FALSE}
p.adjust(corrLeft$pval, method = "fdr", n = 165)
```

## Right Hemisphere
```{r corrections-right, echo = FALSE}
p.adjust(corrRight$pval, method = "fdr", n = 163)
```